"""Regenerate every reported number from raw captures.

    python scripts/reproduce.py            # reuse cached plans in benchmark/plans/ if present
    python scripts/reproduce.py --force    # re-run every capture (live path, ~20 min on RTX 4070)

Each capture runs in its own process (one command per capture, as a user would),
plans are cached under benchmark/plans/<name>/ (committed: they replay
deterministically for the scorer), then everything is scored against tape and
written to benchmark/REPORT.md.
"""
import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
SAMPLE = ROOT.parent  # Cozmo's sample LiDAR folders sit next to the repo (see README)
PLANS = ROOT / "benchmark" / "plans"
RESULTS = ROOT / "benchmark" / "results"

# name, capture, tier, scored against tape?, device
RUNS = [
    ("iphone_lidar_flat", RAW / "iphone/lidar/flat", "lidar", True, "iPhone 17 Pro"),
    ("iphone_lidar_bedroom1_a", RAW / "iphone/lidar/bedroom1_a", "lidar", False, "iPhone 17 Pro"),
    ("iphone_lidar_bedroom1_b", RAW / "iphone/lidar/bedroom1_b", "lidar", False, "iPhone 17 Pro"),
    ("iphone_photo", RAW / "iphone/photos", "photo", True, "iPhone 17 Pro"),
    ("iphone_video", RAW / "iphone/video/IMG_2821.MOV", "video", True, "iPhone 17 Pro"),
    ("oneplus_photo", RAW / "oneplus/photos", "photo", True, "OnePlus 13"),
    ("oneplus_photo_repeat", RAW / "oneplus/photos_repeat", "photo", False, "OnePlus 13"),
    ("oneplus_video", RAW / "oneplus/video/flat_tour_new.mp4", "video", True, "OnePlus 13"),
    ("sample_single_room", SAMPLE / "single_room", "lidar", False, "iPhone Pro (Cozmo sample)"),
    ("sample_floor_only", SAMPLE / "single_scan_floor_only", "lidar", False, "iPhone Pro (Cozmo sample)"),
    ("sample_with_ceiling", SAMPLE / "single_scan_with_ceiling", "lidar", False, "iPhone Pro (Cozmo sample)"),
]


def run(name, capture, tier, force) -> dict | None:
    out = PLANS / name
    plan = out / "plan.json"
    if plan.exists() and not force:
        return json.loads(plan.read_text())
    if not Path(capture).exists():
        print(f"  skip {name}: {capture} not found")
        return None
    t = time.time()
    subprocess.run([sys.executable, "-m", "floorplan", "run", str(capture), "--tier", tier, "--out", str(out)],
                   check=True)
    print(f"  {name}: {time.time() - t:.0f}s")
    return json.loads(plan.read_text())


def extents(room) -> list[float]:
    return sorted(float(x) for x in np.ptp(np.array(room["polygon"]), 0))


def largest_room(plan):
    return max(plan["rooms"], key=lambda r: r["floor_area"]["value"]) if plan and plan["rooms"] else None


def repeatability(a, b, label) -> str:
    """Same room, same tier, two captures: per-axis difference vs gate (1 cm or 0.5 %)."""
    if a is None or b is None:
        return f"| {label} | — | — | — | capture produced no room |"
    ea, eb = extents(a), extents(b)
    rows = []
    for x, y in zip(ea, eb):
        d = abs(x - y)
        ok = d <= max(0.01, 0.005 * max(x, y))
        rows.append(f"{x:.3f} vs {y:.3f} (Δ {100 * d:.1f} cm, {'pass' if ok else 'fail'})")
    return f"| {label} | {rows[0]} | {rows[1]} | | |"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args()
    sys.stdout.reconfigure(encoding="utf-8")
    sys.path.insert(0, str(ROOT / "scripts"))
    import benchmark as B

    gt = B.load_gt(ROOT / "benchmark" / "ground_truth.csv")
    plans, md = {}, ["# Benchmark report (generated by scripts/reproduce.py)", ""]
    for name, cap, tier, scored, device in RUNS:
        plans[name] = run(name, cap, tier, a.force)

    md += ["## Accuracy against tape (benchmark flat: living, bedroom1, bedroom2, hall)", "",
           "| capture | device | tier | rooms | footprint | mean wall err | wall gate | walls in 95% CI | "
           "ceilings ≤1.5 cm | openings ≤2 cm | time s |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    RESULTS.mkdir(parents=True, exist_ok=True)
    for name, cap, tier, scored, device in RUNS:
        p = plans.get(name)
        if not scored or p is None:
            continue
        mapping = B.match_rooms(p, gt, tier, None)
        r = B.score(p, gt, mapping)
        (RESULTS / f"{name}.json").write_text(json.dumps(r, indent=2, default=float))
        (RESULTS / f"{name}.md").write_text(B.to_markdown(r), encoding="utf-8")
        s = r["summary"]
        md.append(f"| {name} | {device} | {tier} | {s['rooms_matched']} | {s['footprint_m2']} | "
                  f"{s['wall_mean_abs_err_pct']}% | {s['wall_gate'] or 'n/a (cm-level, see table)'} | "
                  f"{s['wall_inside_ci95']} | {s['ceiling_within_1.5cm']} | {s['openings_within_2cm']} | "
                  f"{p['capture']['processing_seconds']} |")
    md += ["", "Per-wall tables: `benchmark/results/<capture>.md`.", ""]

    md += ["## Repeatability (same room, same tier, two captures)", "",
           "| room / tier | short side | long side | | |", "|---|---|---|---|---|"]
    ph1 = next((r for r in (plans.get("oneplus_photo") or {}).get("rooms", []) if r["name"] == "bedroom1"), None)
    md.append(repeatability(ph1, largest_room(plans.get("oneplus_photo_repeat")), "bedroom1, photo (OnePlus 13)"))
    md.append(repeatability(largest_room(plans.get("iphone_lidar_bedroom1_a")),
                            largest_room(plans.get("iphone_lidar_bedroom1_b")), "bedroom1, LiDAR (iPhone 17 Pro) a vs b"))
    md += ["", "**Ceiling height, same room captured twice** (gate: spread ≤ 1 cm)", "",
           "| room / tier | capture 1 | capture 2 | spread | gate |", "|---|---|---|---|---|"]
    for label, x, y in (("bedroom1, LiDAR a vs b", largest_room(plans.get("iphone_lidar_bedroom1_a")),
                         largest_room(plans.get("iphone_lidar_bedroom1_b"))),
                        ("bedroom1, photo OnePlus set 1 vs 2", ph1, largest_room(plans.get("oneplus_photo_repeat")))):
        if x and y and x["ceiling_height"] and y["ceiling_height"]:
            a_, b_ = x["ceiling_height"]["value"], y["ceiling_height"]["value"]
            md.append(f"| {label} | {a_:.3f} | {b_:.3f} | {100 * abs(a_ - b_):.1f} cm | "
                      f"{'pass' if abs(a_ - b_) <= 0.01 else 'fail'} |")
        else:
            md.append(f"| {label} | — | — | — | ceiling not observed in one capture |")
    md += ["", "## Timing", "", "| capture | tier | seconds |", "|---|---|---|"]
    for name, cap, tier, scored, device in RUNS:
        p = plans.get(name)
        if p:
            md.append(f"| {name} | {tier} | {p['capture']['processing_seconds']} |")
    try:
        import head_to_head
        head_to_head.main()
        md += ["", "## Head-to-head vs Polycam", "", "See benchmark/HEAD_TO_HEAD.md (regenerated by this script)."]
    except FileNotFoundError:
        md += ["", "## Head-to-head vs Polycam", "", "Polycam export not found (data/raw/iphone/polycam)."]
    (ROOT / "benchmark" / "REPORT.md").write_text("\n".join(md), encoding="utf-8")
    print("\n".join(md))


if __name__ == "__main__":
    main()
